version: "3.5"
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: luiz05012013
      MYSQL_USER: root
      MYSQL_PASSWORD: luiz05012013
      MYSQL_DATABASE: db-softplan-desafio-fullstack-001
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup-001.sql
      - db_data:/var/lib/mysql
volumes:
  db_data:

